version: "3"
services:
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - /sharedEbs/grafana-storage:/var/lib/grafana
  clickhouse:
    image: clickhouse/clickhouse-server
    ports:
      - 8123:8123
      - 9000:9000
      - 9100:9100
      - 9440:9440
    volumes:
      - /sharedEbs/clickhouse-storage:/var/lib/clickhouse/
      - /sharedEbs/clickhouse-logs:/var/log/clickhouse-server
    environment:
      - CLICKHOUSE_USER=tymbaca
      - CLICKHOUSE_PASSWORD=qwerty
