version: "3"
services:
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana
  clickhouse:
    image: clickhouse/clickhouse-server
    ports:
      - 8123:8123
      - 9000:9000
      - 9100:9100
      - 9440:9440
    volumes:
      # - ./run/clickhouse/users.xml:/etc/clickhouse-server/users.xml
      - clickhouse-storage:/var/lib/clickhouse/
      - clickhouse-logs:/var/log/clickhouse-server
    environment:
      - CLICKHOUSE_USER=tymbaca
      - CLICKHOUSE_PASSWORD=qwerty
volumes:
  grafana-storage: 
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/ec2-user/sharedEbs/grafana-storage'
  clickhouse-storage:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/ec2-user/sharedEbs/clickhouse-storage'
  clickhouse-logs:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/ec2-user/sharedEbs/clickhouse-logs'
